---
- name: login 
  hosts: localhost
  environment:
    env_user: rlujan 
    env_password: rlujan 
    env_host: https://vcloud.t-systems.es
    env_org: UnixDept 
    env_api_version: 34.0
    env_verify_ssl_certs: false
  tasks: 
   - name: create vapp vm from catalog
     vcd_vapp_vm:
       target_vm_name: "linux20"
       target_vapp: "vApp_AWX"
       source_vdc: "unix-alloc-vdc-01"
       target_vdc: "unix-alloc-vdc-01"
       source_catalog_name: "Unix"
       source_template_name: "template_OL_8_5"
       source_vm_name: "linux01"
       ip_allocation_mode: "MANUAL"
       power_on: false
       all_eulas_accepted: true
       storage_profile: "Entry SB01B2"
       network: "awxnet"
       deploy: false
       state: "present"
     ignore_errors: true
   - name: modify cpu vapp vm
     vcd_vapp_vm:
       target_vm_name: "linux20"
       target_vapp: "vApp_AWX"
       target_vdc: "unix-alloc-vdc-01"
       virtual_cpus: 2
       cores_per_socket: 2
       state: "update"
   - name: modify memory vapp vm
     vcd_vapp_vm:
       target_vm_name: "linux20"
       target_vapp: "vApp_AWX"
       target_vdc: "unix-alloc-vdc-01"
       memory: 2048
       state: "update"
   - name: create vm nic
     vcd_vapp_vm_nic:
       vm_name: "linux20"
       vapp: "vApp_AWX" 
       vdc: "unix-alloc-vdc-01"
       nics:
       - nic_id: 1
         network: "awxnet"
         ip_allocation_mode: "MANUAL"
         ip_address: "192.168.17.220"
         is_connected: true 
         adapter_type: "VMXNET3"
       state: present
   - name: poweron server
     vcd_vapp_vm:
       target_vm_name: "linux20"
       target_vapp: "vApp_AWX"
       target_vdc: "unix-alloc-vdc-01"
       operation: "poweron" 
     tags: poweron
