---
- name: login 
  hosts: localhost
  environment:
    env_user: rlujan 
    env_password: rlujan 
    env_host: https://vcloud.t-systems.es
    env_org: UnixDept 
    env_api_version: 34.0
    env_verify_ssl_certs: false
  tasks: 
   - name: poweroff vm
     vcd_vapp_vm:
      target_vm_name: "{{ hosts }}" 
      target_vapp: "vApp_AWX"
      target_vdc: "unix-alloc-vdc-01"
      operation: "poweroff"
   - name: destroying vm
     vcd_vapp_vm:
      target_vm_name: "{{ hosts }}"
      target_vapp: "vApp_AWX"
      target_vdc: "unix-alloc-vdc-01"
      state: absent
